export declare type AccoladeData = {
    [key in AccoladeProperty]: number;
};
declare type AccoladeProperty =
    'classChanges' |
    'highestAvgAltitude' |
    'killsFromBehind' |
    'lmgDeaths' |
    'riotShieldDamageAbsorbed' |
    'flashbangHits' |
    'meleeKills' |
    'tagsLargestBank' |
    'shotgunKills' |
    'sniperDeaths' |
    'timeProne' |
    'killstreakWhitePhosphorousKillsAssists' |
    'shortestLife' |
    'deathsFromBehind' |
    'higherRankedKills' |
    'mostAssists' |
    'leastKills' |
    'tagsDenied' |
    'killstreakWheelsonKills' |
    'sniperHeadshots' |
    'killstreakJuggernautKills' |
    'smokesUsed' |
    'avengerKills' |
    'decoyHits' |
    'killstreakCarePackageUsed' |
    'molotovKills' |
    'gasHits' |
    'comebackKills' |
    'lmgHeadshots' |
    'smgDeaths' |
    'carrierKills' |
    'deployableCoverUsed' |
    'revives' |
    'thermiteKills' |
    'arKills' |
    'c4Kills' |
    'suicides' |
    'clutch' |
    'survivorKills' |
    'killstreakGunshipKills' |
    'timeSpentAsPassenger' |
    'returns' |
    'smgHeadshots' |
    'launcherDeaths' |
    'oneShotOneKills' |
    'ammoBoxUsed' |
    'spawnSelectSquad' |
    'weaponPickups' |
    'pointBlankKills' |
    'tagsCaptured' |
    'killstreakGroundKills' |
    'distanceTraveledInVehicle' |
    'longestLife' |
    'stunHits' |
    'spawnSelectFlag' |
    'shotgunHeadshots' |
    'bombDefused' |
    'snapshotHits' |
    'noKillsWithDeath' |
    'killstreakAUAVAssists' |
    'killstreakPersonalUAVKills' |
    'tacticalInsertionSpawns' |
    'launcherKills' |
    'spawnSelectVehicle' |
    'mostKillsLeastDeaths' |
    'mostKills' |
    'defends' |
    'timeSpentAsDriver' |
    'bombDetonated' |
    'arHeadshots' |
    'timeOnPoint' |
    'lmgKills' |
    'killstreakUAVAssists' |
    'carepackagesCaptured' |
    'mostKillsLongestStreak' |
    'killstreakCruiseMissileKills' |
    'longestStreak' |
    'destroyedKillstreaks' |
    'hipfireKills' |
    'stimDamageHealed' |
    'skippedKillcams' |
    'leastAssists' |
    'mostMultikills' |
    'highestRankedKills' |
    'killstreakAirstrikeKills' |
    'distanceTravelled' |
    'killstreakKills' |
    'semtexKills' |
    'penetrationKills' |
    'explosionsSurvived' |
    'highestMultikill' |
    'arDeaths' |
    'longshotKills' |
    'proximityMineKills' |
    'tagsMegaBanked' |
    'mostKillsMostHeadshots' |
    'firstInfected' |
    'killstreakCUAVAssists' |
    'throwingKnifeKills' |
    'executionKills' |
    'lastSurvivor' |
    'reconDroneMarks' |
    'deadSilenceKills' |
    'revengeKills' |
    'infectedKills' |
    'killEnemyTeam' |
    'sniperKills' |
    'killstreakCluserStrikeKills' |
    'meleeDeaths' |
    'timeWatchingKillcams' |
    'killstreakTankKills' |
    'noKillNoDeath' |
    'shotgunDeaths' |
    'killstreakChopperGunnerKills' |
    'shotsFired' |
    'stoppingPowerKills' |
    'pistolPeaths' |
    'killstreakShieldTurretKills' |
    'timeCrouched' |
    'noDeathsFromBehind' |
    'bombPlanted' |
    'setbacks' |
    'smgKills' |
    'claymoreKills' |
    'kills10NoDeaths' |
    'pistolHeadshots' |
    'killstreakVTOLJetKills' |
    'headshots' |
    'mostDeaths' |
    'adsKills' |
    'empDroneHits' |
    'defenderKills' |
    'launcherHeadshots' |
    'timesSelectedAsSquadLeader' |
    'killstreakAirKills' |
    'damageDealt' |
    'assaults' |
    'fragKills' |
    'killstreakEmergencyAirdropUsed' |
    'captures' |
    'killstreakChopperSupportKills' |
    'spawnSelectBase' |
    'noKill10Deaths' |
    'leastDeaths' |
    'killstreakSentryGunKills' |
    'longestTimeSpentOnWeapon' |
    'lowerRankedKills' |
    'trophySystemHits' |
    'clutchRevives' |
    'lowestAvgAltitude' |
    'pickups' |
    'pistolKills' |
    'damageTaken' |
    'reloads';