export declare type StatData = {
    [key in StatProperty]: number;
}
declare type StatProperty = 'recordLongestWinStreak' |
    'recordXpInAMatch' |
    'accuracy' |
    'bestTotalXp' |
    'losses' |
    'totalGamesPlayed' |
    'score' |
    'winLossRatio' |
    'totalShots' |
    'bestScoreXp' |
    'gamesPlayed' |
    'bestSquardKills' |
    'bestSguardWave' |
    'bestConfirmed' |
    'deaths' |
    'wins' |
    'bestSquardCrates' |
    'kdRatio' |
    'bestAssists' |
    'bestFieldgoals' |
    'bestScore' |
    'recordDeathsInAMatch' |
    'scorePerGame' |
    'bestSPM' |
    'bestKillChains' |
    'recordKillsInAMatch' |
    'suicides' |
    'wlRatio' |
    'currentWinStreak' |
    'bestMatchBonusXp' |
    'bestMatchXp' |
    'bestSguardWeaponLevel' |
    'bestKD' |
    'kills' |
    'bestKillsAsInfected' |
    'bestReturns' |
    'bestStabs' |
    'bestKillsAsSurvivor' |
    'timePlayedTotal' |
    'bestDestructions' |
    'headshots' |
    'bestRescues' |
    'assists' |
    'ties' |
    'recordKillStreak' |
    'bestPlants' |
    'misses' |
    'bestDamage' |
    'bestSetbacks' |
    'bestTouchdowns' |
    'scorePerMinute' |
    'bestDeaths' |
    'bestMedalXp' |
    'bestDefends' |
    'bestSquardRevives' |
    'bestKills' |
    'bestDefuses' |
    'bestCaptures' |
    'hits' |
    'bestMiscXp' |
    'bestKillStreak' |
    'bestDenied';